
const labels={es:{appTitle:"Explorador de Videos de Español",country:"País",region:"Región",speaker:"Presentador",level:"Nivel",topic:"Tema",search:"Buscar",searchPlaceholder:"Buscar...",clear:"Limpiar filtros",watch:"Ver video",footer:"Resultados basados en tu selección",noResults:"Sin resultados"},en:{appTitle:"Spanish Video Explorer",country:"Country",region:"Region",speaker:"Speaker",level:"Level",topic:"Topic",search:"Search",searchPlaceholder:"Search...",clear:"Clear filters",watch:"Watch video",footer:"Results based on your selection",noResults:"No results"}};
const COL_ALIASES={ID:["ID","Id","id"],Title:["Title","Título","Titulo"],URL:["URL","Link","Enlace","File","Archivo"],Country:["Country","País","Pais"],Region:["Region","Región","Region/State","Provincia"],Speaker:["Speaker","Presentador","Ponente","Instructor"],Level:["Level","Nivel"],Topic:["Topic","Tema","Gramar Index","Grammar Index","Índice gramatical","Indice gramatical"],Language:["Language","Idioma"],Description:["Description","Descripción","Descripcion","Notes","Note"],Thumbnail:["Thumbnail","Image","Imagen","Thumb","Poster"]};
function pick(o,ks){for(const k of ks){if(Object.prototype.hasOwnProperty.call(o,k)&&String(o[k]).trim()!=="")return String(o[k]).trim()}return""}
function splitList(v){if(!v)return[];return String(v).split(/[;,/|]/).map(x=>x.trim()).filter(Boolean)}
const state={lang:"en",data:[],filters:{country:[],region:[],speaker:[],level:[],topic:[],q:""}};
const els={title:document.getElementById("app-title"),lang:document.getElementById("lang-select"),country:document.getElementById("country-filter"),region:document.getElementById("region-filter"),speaker:document.getElementById("speaker-filter"),level:document.getElementById("level-filter"),topic:document.getElementById("topic-filter"),search:document.getElementById("search-input"),clear:document.getElementById("clear-btn"),results:document.getElementById("results"),lblCountry:document.getElementById("lbl-country"),lblRegion:document.getElementById("lbl-region"),lblSpeaker:document.getElementById("lbl-speaker"),lblLevel:document.getElementById("lbl-level"),lblTopic:document.getElementById("lbl-topic"),lblSearch:document.getElementById("lbl-search"),footerNote:document.getElementById("footer-note"),cardTpl:document.getElementById("card-template")};
function t(k){return labels[state.lang][k]}
function setTexts(){els.title.textContent=t("appTitle");els.lblCountry.textContent=t("country");els.lblRegion.textContent=t("region");els.lblSpeaker.textContent=t("speaker");els.lblLevel.textContent=t("level");els.lblTopic.textContent=t("topic");els.lblSearch.textContent=t("search");els.search.placeholder=t("searchPlaceholder");els.clear.textContent=t("clear");els.footerNote.textContent=t("footer")}
function uniqueValuesFromArrays(arr,getArr){const s=new Set();arr.forEach(r=>{getArr(r).forEach(v=>s.add(v))});return Array.from(s).sort((a,b)=>a.localeCompare(b))}
function fillMultiSelect(el,vals){el.innerHTML="";vals.forEach(v=>{if(!v)return;const o=document.createElement("option");o.value=v;o.textContent=v;el.appendChild(o)});el.selectedIndex=-1}
function getSelected(el){return Array.from(el.selectedOptions).map(o=>o.value)}
function intersects(a,b){if(a.length===0||b.length===0)return true;return a.some(x=>b.includes(x))}
function applyFilters(){const f=state.filters;const q=f.q.toLowerCase();const out=state.data.filter(r=>{const text=[r.Title,r.Description,r.Speaker.join(", "),r.Country.join(", "),r.Region.join(", "),r.Level.join(", "),r.Topic.join(", ")].join(" ").toLowerCase();return intersects(r.Country,f.country)&&intersects(r.Region,f.region)&&intersects(r.Speaker,f.speaker)&&intersects(r.Level,f.level)&&intersects(r.Topic,f.topic)&&(q===""||text.includes(q))});render(out)}
function render(rows){els.results.innerHTML="";if(rows.length===0){const p=document.createElement("p");p.textContent=t("noResults");p.className="meta";els.results.appendChild(p);return}rows.forEach(r=>{const n=els.cardTpl.content.cloneNode(true);const thumb=n.querySelector(".thumb");const title=n.querySelector(".title");const meta=n.querySelector(".meta");const desc=n.querySelector(".desc");const btn=n.querySelector(".btn");title.textContent=r.Title||"";meta.textContent=[r.Speaker.join(" / "),r.Country.join(" / "),r.Region.join(" / "),r.Level.join(" / "),r.Topic.join(" / ")].filter(Boolean).join(" · ");desc.textContent=r.Description||"";btn.textContent=t("watch");btn.href=r.URL||"#";if(r.Thumbnail){thumb.style.backgroundImage=`url('${r.Thumbnail}')`;thumb.style.backgroundSize="cover";thumb.style.backgroundPosition="center"}else{thumb.setAttribute("aria-label",r.Title||"")}els.results.appendChild(n)})}
function clearFilters(){state.filters={country:[],region:[],speaker:[],level:[],topic:[],q:""};for(const el of[els.country,els.region,els.speaker,els.level,els.topic])el.selectedIndex=-1;els.search.value="";applyFilters()}
async function fetchText(url){const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error("Fetch failed: "+r.status);return await r.text()}
async function loadData(){let csv="";if(typeof window.DATA_CSV_URL==="string"&&window.DATA_CSV_URL.trim()!==""){try{csv=await fetchText(window.DATA_CSV_URL.trim())}catch(e){console.warn("Live CSV failed; fallback to data.csv",e);csv=await fetchText("data.csv")}}else{csv=await fetchText("data.csv")}const parsed=Papa.parse(csv,{header:true,skipEmptyLines:"greedy",transformHeader:h=>String(h).replace(/^\ufeff/,'').trim()});const rows=parsed.data.map(row=>{const Title=pick(row,COL_ALIASES.Title);const URL=pick(row,COL_ALIASES.URL);return{ID:pick(row,COL_ALIASES.ID),Title,URL,Country:splitList(pick(row,COL_ALIASES.Country)),Region:splitList(pick(row,COL_ALIASES.Region)),Speaker:splitList(pick(row,COL_ALIASES.Speaker)),Level:splitList(pick(row,COL_ALIASES.Level)),Topic:splitList(pick(row,COL_ALIASES.Topic)),Language:pick(row,COL_ALIASES.Language),Description:pick(row,COL_ALIASES.Description),Thumbnail:pick(row,COL_ALIASES.Thumbnail)}}).filter(r=>r.Title||r.URL);state.data=rows;fillMultiSelect(els.country,uniqueValuesFromArrays(rows,r=>r.Country));fillMultiSelect(els.region,uniqueValuesFromArrays(rows,r=>r.Region));fillMultiSelect(els.speaker,uniqueValuesFromArrays(rows,r=>r.Speaker));fillMultiSelect(els.level,uniqueValuesFromArrays(rows,r=>r.Level));fillMultiSelect(els.topic,uniqueValuesFromArrays(rows,r=>r.Topic));applyFilters()}
function bindEvents(){els.lang.addEventListener("change",()=>{state.lang=els.lang.value;setTexts();applyFilters()});els.country.addEventListener("change",()=>{state.filters.country=getSelected(els.country);applyFilters()});els.region.addEventListener("change",()=>{state.filters.region=getSelected(els.region);applyFilters()});els.speaker.addEventListener("change",()=>{state.filters.speaker=getSelected(els.speaker);applyFilters()});els.level.addEventListener("change",()=>{state.filters.level=getSelected(els.level);applyFilters()});els.topic.addEventListener("change",()=>{state.filters.topic=getSelected(els.topic);applyFilters()});els.search.addEventListener("input",()=>{state.filters.q=els.search.value.trim().toLowerCase();applyFilters()});els.clear.addEventListener("click",clearFilters)}
document.addEventListener("DOMContentLoaded",async()=>{setTexts();bindEvents();await loadData()});
